<template>
	<div class="mainNavs">
		<div v-for="part in menulist">
			<menubox :part='part'></menubox>
		</div>
	</div>
</template>

<script>
	import menubox from './menubox.vue'
	export default{
		name:'mainNavs',
		components:{menubox},
		data(){
			return{
				menulist:[
					{
						main:{
							type:'技术',
							joblist:[
								{name:'Java',path:''},
								{name:'PHP',path:''},
								{name:'C',path:''},
								{name:'C++',path:''},
								{name:'Android',path:''},
								{name:'IOS',path:''},
								{name:'前端开发',path:''},
								{name:'测试',path:''},
								{name:'技术经理',path:''},
								{name:'项目经理',path:''},
								{name:'架构师',path:''},
							]
						},
						sub:[
							{
								type:'后端开发',
								joblist:[
									{name:'Java',path:''},
									{name:'C++',path:''},
									{name:'PHP',path:''},
									{name:'数据挖掘',path:''},
									{name:'C',path:''},
									{name:'C#',path:''},
									{name:'.NET',path:''},
									{name:'Hadoop',path:''},
									{name:'Python',path:''},
									{name:'Delphi',path:''},
									{name:'VB',path:''},
									{name:'Perl',path:''},
									{name:'Ruby',path:''},
									{name:'Node.js',path:''},
								]
							},
							{
								type:'移动开发',
								joblist:[
									{name:'HTML5',path:''},
									{name:'Android',path:''},
									{name:'IOS',path:''},
									{name:'WP',path:''},
								]
							},
							{
								type:'前端开发',
								joblist:[
									{name:'web前端',path:''},
									{name:'Flash',path:''},
									{name:'HTML5',path:''},
									{name:'JavaScript',path:''},
									{name:'U3D',path:''},
									{name:'COCOS2D-X',path:''},
								]
							},
							{
								type:'测试',
								joblist:[
									{name:'测试工程师',path:''},
									{name:'自动化测试',path:''},
									{name:'功能测试',path:''},
									{name:'性能测试',path:''},
									{name:'测试开发',path:''},
								]
							},
							{
								type:'运维',
								joblist:[
									{name:'运维工程师',path:''},
									{name:'运维开发工程师',path:''},
									{name:'网络工程师',path:''},
									{name:'系统工程师',path:''},
									{name:'IT支持',path:''},
								]
							},
							{
								type:'DBA',
								joblist:[
									{name:'MySQL',path:''},
									{name:'SQLServer',path:''},
									{name:'Oracle',path:''},
									{name:'DB2',path:''},
									{name:'Mongo',path:''},
								]
							},
							{
								type:'项目管理',
								joblist:[
									{name:'项目经理',path:''},
									{name:'项目支持',path:''},
								]
							},
							{
								type:'高端职位',
								joblist:[
									{name:'技术经理',path:''},
									{name:'技术总监',path:''},
									{name:'测试经理',path:''},
									{name:'架构师',path:''},
									{name:'CTO',path:''},
									{name:'运维总监',path:''},
								]
							},
						]
					},
					{
						main:{
							type:'产品',
							joblist:[
								{name:'产品经理',path:''},
								{name:'产品助理',path:''},
								{name:'无线产品经理',path:''},
								{name:'游戏策划',path:''},
								
							]
						},
						sub:[
							{
								type:'产品经理',
								joblist:[
									{name:'产品经理',path:''},
									{name:'网页产品经理',path:''},
									{name:'移动产品经理',path:''},
									{name:'产品助理',path:''},
									{name:'数据产品助理',path:''},
									{name:'电商产品经理',path:''},
									{name:'游戏策划',path:''},
								]
							},
							{
								type:'产品设计师',
								joblist:[
									{name:'网页产品设计师',path:''},
									{name:'无线产品设计师',path:''}
								]
							},
							{
								type:'高端职位',
								joblist:[
									{name:'产品部经理',path:''},
									{name:'产品经理',path:''}
								]
							},
						]
					},
					{
						main:{
							type:'设计',
							joblist:[
								{name:'UI',path:''},
								{name:'UE',path:''},
								{name:'设计师',path:''},
								{name:'交互设计',path:''},
								{name:'数据分析',path:''},
							]
						},
						sub:[
							{
								type:'视觉设计',
								joblist:[
									{name:'视觉设计师',path:''},
									{name:'网页设计师',path:''},
									{name:'Flash设计师',path:''},
									{name:'APP设计师',path:''},
									{name:'UI设计师',path:''},
									{name:'平面设计师',path:''},
									{name:'美术设计师',path:''}
								]
							},
							{
								type:'交互设计',
								joblist:[
									{name:'交互设计师',path:''},
									{name:'无线交互设计师',path:''},
									{name:'网页交互设计师',path:''},
									{name:'硬件交互设计师',path:''}
								]
							},
							{
								type:'用户研究',
								joblist:[
									{name:'数据分析师',path:''},
									{name:'用户研究员',path:''},
									{name:'游戏数值策划',path:''}
								]
							},
							{
								type:'高端职位',
								joblist:[
									{name:'设计经理/主管',path:''},
									{name:'设计总监',path:''},
									{name:'视觉设计经理/主管',path:''},
									{name:'交互设计总监',path:''},
									{name:'用户研究总监',path:''}
								]
							}
						]
					},
					{
						main:{
							type:'运营',
							joblist:[
								{name:'运营',path:''},
								{name:'游戏运营',path:''},
								{name:'编辑',path:''}
							]
						},
						sub:[
							{
								type:'运营',
								joblist:[
									{name:'用户运营',path:''},
									{name:'产品运营',path:''},
									{name:'数据运营',path:''},
									{name:'内容运营',path:''},
									{name:'活动运营',path:''},
									{name:'商家运营',path:''},
									{name:'游戏运营',path:''},
									{name:'网络推广',path:''}
								]
							},
							{
								type:'客服',
								joblist:[
									{name:'售前咨询',path:''},
									{name:'售后服务',path:''}
								]
							},
							{
								type:'编辑',
								joblist:[
									{name:'审稿',path:''},
									{name:'内容编辑',path:''}
								]
							},
							{
								type:'高端职位',
								joblist:[
									{name:'主编',path:''},
									{name:'COO',path:''},
									{name:'运营总监',path:''}
								]
							}
						]
					},
					{
						main:{
							type:'市场与销售',
							joblist:[
								{name:'市场推广',path:''},
								{name:'市场策划',path:''},
								{name:'活动策划',path:''},
								{name:'BD',path:''},
								{name:'销售经理',path:''}
							]
						},
						sub:[
							{
								type:'市场',
								joblist:[
									{name:'市场营销',path:''},
									{name:'市场推广',path:''},
									{name:'市场策划',path:''},
									{name:'市场顾问',path:''},
									{name:'SEO',path:''},
									{name:'SEM',path:''},
									{name:'商务渠道',path:''},
									{name:'商业数据分析',path:''}
								]
							},
							{
								type:'公关',
								joblist:[
									{name:'媒介经理',path:''},
									{name:'广告协调',path:''},
									{name:'品牌公关',path:''}
								]
							},
							{
								type:'销售',
								joblist:[
									{name:'销售专员',path:''},
									{name:'销售经理',path:''},
									{name:'客户代表',path:''}
								]
							},
							{
								type:'高端职位',
								joblist:[
									{name:'市场总监',path:''},
									{name:'销售总监',path:''},
									{name:'商务总监',paht:''}
								]
							}
						]
					},
					{
						main:{
							type:'职能',
							joblist:[
								{name:'HR',path:''},
								{name:'行政',path:''},
								{name:'会计',path:''},
								{name:'出纳',path:''}
							]
						},
						sub:[
							{
								type:'人力资源',
								joblist:[
									{name:'招聘',path:''},
									{name:'HRBP',path:''},
									{name:'人事/HR',path:''},
									{name:'培训经理',path:''},
									{name:'绩效考核经理',path:''}
								]
							},
							{
								type:'行政',
								joblist:[
									{name:'助理',path:''},
									{name:'前台',path:''},
									{name:'法务',path:''}
								]
							},
							{
								type:'财务',
								joblist:[
									{name:'会计',path:''},
									{name:'出纳',path:''},
									{name:'财务管理',path:''}
								]
							},
							{
								type:'高端职位',
								joblist:[
									{name:'行政总监/经理',path:''},
									{name:'财务总监/经理',path:''},
									{name:'CFO',path:''}
								]
							}
						]
					},
				]
			}
		}
	}
</script>

<style>
</style>